/* Generated by tex3ds */
#pragma once

#define blocks_bedrock_idx 0
#define blocks_brick_idx 1
#define blocks_cobblestone_idx 2
#define blocks_dirt_idx 3
#define blocks_glass_idx 4
#define blocks_grass_block_side_idx 5
#define blocks_grass_block_top_idx 6
#define blocks_leaves_oak_idx 7
#define blocks_log_oak_idx 8
#define blocks_log_oak_top_idx 9
#define blocks_planks_oak_idx 10
#define blocks_sand_idx 11
#define blocks_smooth_stone_idx 12
#define blocks_smooth_stone_slab_side_idx 13
#define blocks_stone_idx 14
#define blocks_stone_bricks_idx 15
#define blocks_wool_idx 16
